## w Pre-fusion + Attention

model:
  arch: nano_emox
  model_type: pretrain_vicuna

  # Audio Q-Former and Video Q-Former
  frozen_video_Qformer: False
  frozen_audio_Qformer: False
  frozen_multi_Qformer: False
  frozen_multi_MoE: False

  frozen_audio_proj: False
  frozen_video_proj: False
  frozen_multi_llama_proj: False
  frozen_facial_llama_proj: False
  
  frozen_llm: False

  multi_fusion_type: multiscale # attention/qformer/densemoe/multiscale
  video_fusion_type: qformer # qformer(default)/mean/attention
  audio_fusion_type: qformer # qformer(default)/mean/attention
  image_fusion_type: mean       # token(default)/mean

  # 模型初始化权重
  ckpt: 
  ckpt_2:
  
  # Other pre-trained models
  llama_model: "Qwen25"            # Vicuna
  acoustic_encoder: "HUBERT_LARGE_Plus" # IMAGEBIND /HUBERT_LARGE_Plus
  visual_encoder: "CLIP_VIT_LARGE_Plus" # EVA_CLIP_G /HUBERT_LARGE_Plus

  # LoRA configuration
  lora_r: 16        
  lora_alpha: 32      
  lora_dropout: 0.05 

  # token num of modality
  num_audio_query_token: 32
  num_video_query_token: 32
  num_multi_query_token: 1
  num_facial_query_token: 4
  num_image_query_token: 1

  max_length: 1024

  vis_processor:
    train:
      name: "alpro_video_train"
      n_frms: 8
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
  img_processor:
    train:
      name: "blip2_image_train"
      image_size: 224
  

datasets: 
# modality ablation:
# ---------音频、视频、文本面部------
# faceframe (face, video, audio, text) | face (face, audio, text) | frame  (video, audio, text)
# ---------融合、音频、视频、文本面部-----------------
# multiframe_audio_frame_text (multi, video, audio, text)
# multiface_audio_face_frame_text (multi, frame, face, audio, text)
  mercaptionplus:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text' # 指定输入的模态，multiframe_audio_frame_text，multiface_audio_face_text
    label_type: 'hybird' # 模型是预测 description 还是 label 呢？
    ratio: 0.55 
  
  merrfine:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text' 
    label_type: 'description' # 模型是预测 description 还是 label 呢？
    ratio: 0.05 
  
  mintrec:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text'
    label_type: 'intent_recognition'
    ratio: 0.02

  mintrec2:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text'
    label_type: 'intent_recognition' 
    ratio: 0.03

  avamerg:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text'
    label_type: 'hybird' #  'empathic_response_with_coe','emotion_recognition'
    ratio: 0.35

  # meld_train:
  #   data_type: video
  #   face_or_frame: 'multiface_audio_face_frame_text'
  #   label_type: 'emotion_recognition' # emotion_clue_analysis,comprehensive_emotion_reasoning
  #   ratio: 0.05
  
  # iemocap_train:
  #   data_type: video
  #   face_or_frame: 'multiface_audio_face_frame_text'
  #   label_type: 'emotion_recognition' # emotion_clue_analysis,comprehensive_emotion_reasoning
  #   ratio: 0.1

# 1. 采用大batch + 三个 80g gpu 
run:
  task: video_text_pretrain

  # optimizer CAdamW
  lr_sched: "linear_warmup_cosine_lr"
  init_lr:1e-5 # 3e-5 loss: nan -> 降低 loss 到 2e-5 nan -> 降低 loss 到 1e-5 训练moe时候1e-5 ->nan 降低到5e-6
  min_lr:1e-5 # 1e-5
  warmup_lr: 5e-7 #  1e-6
  weight_decay: 0.05

  max_epoch: 60
  iters_per_epoch: 5000 # 1000 5000
  warmup_steps: 5000    # 1000 5000

  batch_size_train: 3 # 3 # 这是单一gpu的batch_size；实际batch_size = gpu_num * batch_size_train
  batch_size_eval:  3 # 3 # 这是单一gpu的batch_size；实际batch_size = gpu_num * batch_size_train

  seed: 42
  num_workers: 2 # 1 2 4

  # auto mixed precision, multiplication (fp16), addition (fp32)
  amp: True 
  # continue training from resume_ckpt_path "/path/ckpt" or null
  resume_ckpt_path: #"output/nano_emox_mercaption_outputhybird/nano_emox_mercaption_outputhybird_20250823220/checkpoint_000032_loss_0.314.pth"

  evaluate: False 
  train_splits: ["train"]

  device: "cuda" 
  world_size: 1
  dist_url: "env://"
  distributed: True


# 这部分放的是 inference 相关的
inference:

  task: video_text_pretrain

  vis_processor:
    train:
      name: "alpro_video_eval"
      n_frms: 8
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
  img_processor:
    train:
      name: "blip2_image_eval"
      image_size: 224

  ######################################################
  # NOTE: 为了避免出错，设置为与 emercoarse 或者 mer2023 一致就可以，消融时候记得改成和训练的一样
  face_or_frame: 'emercoarse'
  ######################################################

  base_root: 'output/results'
  
  # inference ckpt
  # ckpt_root: "output/nano_emox_mercaption_outputhybird/nano_emox_mercaption_outputhybird_20250729215"
  # ckpt_name: "checkpoint_000040_loss_0.385.pth"
  ckpt_root: "output/nano_emox_mercaption_outputhybird/"
  ckpt_name: 
  test_epoch: xxx # 指定跑哪个轮次 默认xxx
  test_epochs: xxx-xxx # 指定跑一批轮次
  skip_epoch: 1 # only process on epoch%10=0 的部分 ckpt_3
  gpu: 0

