model:
  arch: nano_emox
  model_type: pretrain_vicuna

  # Audio Q-Former and Video Q-Former
  frozen_video_Qformer: False
  frozen_audio_Qformer: False
  frozen_multi_Qformer: False
  frozen_multi_MoE: False
  frozen_multi_multiscale: False
  frozen_facial_encoder: False

  frozen_audio_proj: False
  frozen_video_proj: False
  frozen_multi_llama_proj: False
  frozen_facial_llama_proj: False
  
  frozen_llm: True

  multi_fusion_type: multiscale # attention/qformer/densemoe/multiscale
  video_fusion_type: qformer # qformer(default)/mean/attention
  audio_fusion_type: qformer # qformer(default)/mean/attention
  image_fusion_type: mean       # token(default)/mean

  # 权重初始化
  ckpt: "output/xemo_phase1/xemo_phase1_20250902214/checkpoint_000003_loss_0.129.pth" # 先加载音频分支
  ckpt_2: "output/xemo_phase2/xemo_phase2_20250902234/checkpoint_000005_loss_0.178.pth" # 再加载视频分支
  
  # target_modules 在代码中自动设置为所有注意力和MLP层

  # Other pre-trained models
  llama_model: "Qwen25"            # Vicuna
  acoustic_encoder: "HUBERT_LARGE_Plus" # HUBERT_LARGE / HUBERT_LARGE_Plus
  visual_encoder: "CLIP_VIT_LARGE_Plus" # CLIP_VIT_LARGE / CLIP_VIT_LARGE_Plus

  # LoRA configuration
  lora_r: 16        
  lora_alpha: 32      
  lora_dropout: 0.05 

  # token num of modality
  num_audio_query_token: 32 # 32 / 8的话性能下降2个点
  num_video_query_token: 32 # 32 / 8的话性能下降2个点
  num_multi_query_token: 1
  num_facial_query_token: 4
  num_image_query_token: 1

  max_length: 1024

  vis_processor:
    train:
      name: "alpro_video_train"
      n_frms: 8
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
  img_processor:
    train:
      name: "blip2_image_train"
      image_size: 224
  

datasets:
# ablation:audio_text face_text,frame_text,face_frame_text,faceframe
  mintrec:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text'
    label_type: 'intent_recognition'

  mintrec2:
    data_type: video
    face_or_frame: 'multiface_audio_face_frame_text'
    label_type: 'intent_recognition' 

# 1. 采用大batch + 三个 80g gpu 
run:

  task: video_text_pretrain

  # optimizer CAdamW
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5 # 3e-5 loss: nan -> 降低 loss 到 2e-5 nan -> 降低 loss 到 1e-5 训练moe时候1e-5 ->nan 降低到5e-6
  min_lr: 1e-5 # 1e-5
  warmup_lr: 5e-7 #  1e-6
  weight_decay: 0.05

  max_epoch: 1 # 20 -> 100 大概可以让每个样本跑2-3次的样子，因为 EMER-Coarse 大约有 11.5k samples => 大约 26h 就可以跑完，速度还ok的
  iters_per_epoch: 5000 # 1000 5000
  warmup_steps: 5000    # 1000 5000

  batch_size_train: 3 # 3 # 这是单一gpu的batch_size；实际batch_size = gpu_num * batch_size_train
  batch_size_eval:  3 # 3 # 这是单一gpu的batch_size；实际batch_size = gpu_num * batch_size_train

  seed: 42
  num_workers: 3 # 1 2 4

  # auto mixed precision, multiplication (fp16), addition (fp32)
  amp: True 
  # continue training from resume_ckpt_path "/path/ckpt" or null
  resume_ckpt_path: #"output/xemo_phase3/xemo_phase3_20250903210/checkpoint_000022_loss_0.324.pth"

  evaluate: False 
  train_splits: ["train"]

  device: "cuda" 
  world_size: 1
  dist_url: "env://"
  distributed: True


# 这部分放的是 inference 相关的
inference:

  task: video_text_pretrain

  vis_processor:
    train:
      name: "alpro_video_eval"
      n_frms: 8
      image_size: 224
  text_processor:
    train:
      name: "blip_caption"
  img_processor:
    train:
      name: "blip2_image_eval"
      image_size: 224

  ######################################################
  # NOTE: 为了避免出错，设置为与 emercoarse 或者 mer2023 一致就可以
  face_or_frame: 'emercoarse'
  ######################################################

  base_root: 'output/results'
  
  # inference ckpt
  # ckpt_root: "output/nano_emox_mercaption_outputhybird/nano_emox_mercaption_outputhybird_20250711175"
  # ckpt_name: "checkpoint_000041_loss_0.934.pth"
  ckpt_root: "output/xemo_phase3/xemo_phase3_20251031203"
  ckpt_name:
  test_epoch: 1 # 指定跑哪个轮次 默认xxx
  test_epochs: xxx-xxx # 指定跑一批轮次
  skip_epoch: 1 # only process on epoch%10=0 的部分  
  gpu: 0

